# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170602_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.TextField(blank=True),
        ),
    ]
