# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_profile', '0002_auto_20170525_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='likes',
        ),
    ]
