# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_profile', '0005_auto_20170601_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='follows_change',
        ),
    ]
